### ISSUE TITLE
Aprendiendo Issues en clase 1

### ISSUE THREAD

**Issue by jaimerabasco** [albertommartinez/programacion2019-20#1]
Cambia la foto de perfil!!!! @albertommartinez

**Comment by hipema** [comment]
Una de la comunión estaría bien

**Comment by albertommartinez** [comment]
Sí, la tengo que cambiar, pero como soy un Gnomo malo buscare una potente

**Comment by rafacab1** [comment]
El aire acondicionado que tienes detrás va bien? Es que me quiero pillar uno

**Comment by albertommartinez** [comment]
va de lujo, es del pryca
